// scripts/generate-case-studies-manifest.ts
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const caseStudyDir = join(__dirname, '..', 'ref_src', 'case_studies')
const outputPath = join(__dirname, '..', 'src', 'data', 'case-studies-manifest.ts')

interface ManifestEntry {
  id: string
  locales: ('en' | 'zh-TW')[]
}

function buildManifest(): Record<string, ManifestEntry> {
  const entries: Record<string, ManifestEntry> = {}
  let files: string[] = []
  try {
    files = readdirSync(caseStudyDir).filter(f => f.endsWith('.md'))
  } catch {
    return entries
  }
  for (const file of files) {
    if (file === '_template.md' || file.startsWith('example_')) continue
    const m = file.match(/^([a-zA-Z0-9_]+)\.(en|zh-TW)\.md$/)
    if (!m) continue
    const [, id, locale] = m
    if (!entries[id]) entries[id] = { id, locales: [] }
    entries[id].locales.push(locale as 'en' | 'zh-TW')
  }
  return entries
}

const manifest = buildManifest()
const body = [
  '// AUTO-GENERATED by scripts/generate-case-studies-manifest.ts. Do not edit.',
  '',
  'export type CaseStudyManifestEntry = {',
  '  id: string',
  '  locales: (\'en\' | \'zh-TW\')[]',
  '}',
  '',
  `export const caseStudiesManifest: Record<string, CaseStudyManifestEntry> = ${JSON.stringify(manifest, null, 2)}`,
  '',
].join('\n')

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, body)
console.log(`[manifest] generated ${Object.keys(manifest).length} entries → ${outputPath}`)
